-- MySQL Script generated by MySQL Workbench
-- Fri Feb 28 10:05:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loans
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `loans` ;

-- -----------------------------------------------------
-- Schema loans
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loans` DEFAULT CHARACTER SET utf8 ;
USE `loans` ;

-- -----------------------------------------------------
-- Table `loans`.`mailing_addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loans`.`mailing_addresses` ;

CREATE TABLE IF NOT EXISTS `loans`.`mailing_addresses` (
  `mailing_addresses_id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `zip` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`mailing_addresses_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loans`.`account_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loans`.`account_types` ;

CREATE TABLE IF NOT EXISTS `loans`.`account_types` (
  `account_types_id` INT NOT NULL AUTO_INCREMENT,
  `account_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_types_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loans`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loans`.`accounts` ;

CREATE TABLE IF NOT EXISTS `loans`.`accounts` (
  `accounts_id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `account_types_id` INT NOT NULL,
  PRIMARY KEY (`accounts_id`),
  INDEX `fk_accounts_account_types1_idx` (`account_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_accounts_account_types1`
    FOREIGN KEY (`account_types_id`)
    REFERENCES `loans`.`account_types` (`account_types_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loans`.`user_profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loans`.`user_profiles` ;

CREATE TABLE IF NOT EXISTS `loans`.`user_profiles` (
  `user_profiles_id` INT NOT NULL AUTO_INCREMENT,
  `accounts_id` INT NOT NULL,
  `mailing_addresses_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  `credit_score` INT(4) NOT NULL,
  `birth_date` DATE NOT NULL,
  PRIMARY KEY (`user_profiles_id`),
  INDEX `fk_user_profiles_mailing_addresses1_idx` (`mailing_addresses_id` ASC) VISIBLE,
  INDEX `fk_user_profiles_accounts1_idx` (`accounts_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_profiles_mailing_addresses1`
    FOREIGN KEY (`mailing_addresses_id`)
    REFERENCES `loans`.`mailing_addresses` (`mailing_addresses_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_profiles_accounts1`
    FOREIGN KEY (`accounts_id`)
    REFERENCES `loans`.`accounts` (`accounts_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loans`.`application_statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loans`.`application_statuses` ;

CREATE TABLE IF NOT EXISTS `loans`.`application_statuses` (
  `application_statuses_id` INT NOT NULL AUTO_INCREMENT,
  `application_statuses` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`application_statuses_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loans`.`loan_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loans`.`loan_type` ;

CREATE TABLE IF NOT EXISTS `loans`.`loan_type` (
  `loan_type_id` INT NOT NULL AUTO_INCREMENT,
  `loan_type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`loan_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loans`.`loan_applications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loans`.`loan_applications` ;

CREATE TABLE IF NOT EXISTS `loans`.`loan_applications` (
  `loan_applications_id` INT NOT NULL AUTO_INCREMENT,
  `loan_type_id` INT NOT NULL,
  `application_statuses_id` INT NOT NULL,
  `user_profiles_id` INT NOT NULL,
  `principal_balance` FLOAT NOT NULL,
  `interest` FLOAT(8) NOT NULL,
  `term_length` INT(4) NOT NULL,
  `total_balance` FLOAT NOT NULL,
  `borrower` VARCHAR(45) NOT NULL,
  `application_date` DATETIME NOT NULL,
  PRIMARY KEY (`loan_applications_id`),
  INDEX `fk_loan_applications_loan_type1_idx` (`loan_type_id` ASC) VISIBLE,
  INDEX `fk_loan_applications_application_statuses1_idx` (`application_statuses_id` ASC) VISIBLE,
  INDEX `fk_loan_applications_user_profiles1_idx` (`user_profiles_id` ASC) VISIBLE,
  CONSTRAINT `fk_loan_applications_loan_type1`
    FOREIGN KEY (`loan_type_id`)
    REFERENCES `loans`.`loan_type` (`loan_type_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_loan_applications_application_statuses1`
    FOREIGN KEY (`application_statuses_id`)
    REFERENCES `loans`.`application_statuses` (`application_statuses_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_loan_applications_user_profiles1`
    FOREIGN KEY (`user_profiles_id`)
    REFERENCES `loans`.`user_profiles` (`user_profiles_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
